// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEsfRIki8rHSgidRh54a8grHqOMra-MeM',
    appId: '1:337291136715:web:436494570d5a8a9e30154e',
    messagingSenderId: '337291136715',
    projectId: 'trial-b8c93',
    authDomain: 'trial-b8c93.firebaseapp.com',
    storageBucket: 'trial-b8c93.appspot.com',
    measurementId: 'G-DCMBX4LPWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACM6jvx8sF-FwKznINDZtxxP4RAbJpPx0',
    appId: '1:337291136715:android:6e5d5a6c15ae81e130154e',
    messagingSenderId: '337291136715',
    projectId: 'trial-b8c93',
    storageBucket: 'trial-b8c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzmCLMsZFqbX0nTHIWh9ZEP5jNzz4rouI',
    appId: '1:337291136715:ios:ac0f86e00902791b30154e',
    messagingSenderId: '337291136715',
    projectId: 'trial-b8c93',
    storageBucket: 'trial-b8c93.appspot.com',
    iosBundleId: 'com.example.trial',
  );

}